
const irregularVerbs = [
    "arise - arose - arisen",
    "awake - awoke - awoken",
    "be - was/were - been",
    "bear - bore - borne",
    "beat - beat - beaten",
    "become - became - become",
    "begin - began - begun",
    "bend - bent - bent",
    "bet - bet - bet",
    "bind - bound - bound",
    "bite - bit - bitten",
    "bleed - bled - bled",
    "blow - blew - blown",
    "break - broke - broken",
    "bring - brought - brought",
    "broadcast - broadcast - broadcast",
    "build - built - built",
    "burn - burnt/burned - burnt/burned",
    "burst - burst - burst",
    "buy - bought - bought",
    "catch - caught - caught",
    "choose - chose - chosen",
    "come - came - come",
    "cost - cost - cost",
    "cut - cut - cut",
    "deal - dealt - dealt",
    "dig - dug - dug",
    "do - did - done",
    "draw - drew - drawn",
    "dream - dreamt/dreamed - dreamt/dreamed",
    "drink - drank - drunk",
    "drive - drove - driven",
    "eat - ate - eaten",
    "fall - fell - fallen",
    "feed - fed - fed",
    "feel - felt - felt",
    "fight - fought - fought",
    "find - found - found",
    "fly - flew - flown",
    "forget - forgot - forgotten",
    "forgive - forgave - forgiven",
    "freeze - froze - frozen",
    "get - got - gotten",
    "give - gave - given",
    "go - went - gone",
    "grow - grew - grown",
    "hang - hung - hung",
    "have - had - had",
    "hear - heard - heard",
    "hide - hid - hidden",
    "hit - hit - hit",
    "hold - held - held",
    "hurt - hurt - hurt",
    "keep - kept - kept",
    "know - knew - known",
    "lay - laid - laid",
    "lead - led - led",
    "leave - left - left",
    "lend - lent - lent",
    "let - let - let",
    "lie - lay - lain",
    "lose - lost - lost",
    "make - made - made",
    "mean - meant - meant",
    "meet - met - met",
    "pay - paid - paid",
    "put - put - put",
    "read - read - read",
    "ride - rode - ridden",
    "ring - rang - rung",
    "rise - rose - risen",
    "run - ran - run",
    "say - said - said",
    "see - saw - seen",
    "sell - sold - sold",
    "send - sent - sent",
    "set - set - set",
    "shake - shook - shaken",
    "shine - shone - shone",
    "shoot - shot - shot",
    "show - showed - shown",
    "shut - shut - shut",
    "sing - sang - sung",
    "sink - sank - sunk",
    "sit - sat - sat",
    "sleep - slept - slept",
    "speak - spoke - spoken",
    "spend - spent - spent",
    "stand - stood - stood",
    "steal - stole - stolen",
    "stick - stuck - stuck",
    "strike - struck - struck",
    "swear - swore - sworn",
    "sweep - swept - swept",
    "swim - swam - swum",
    "take - took - taken",
    "teach - taught - taught",
    "tear - tore - torn",
    "tell - told - told",
    "think - thought - thought",
    "throw - threw - thrown",
    "understand - understood - understood",
    "wake - woke - woken",
    "wear - wore - worn",
    "win - won - won",
    "write - wrote - written"
];


function inpute(e) {
    const inputValue = e.value.toLowerCase();
    const h1 = document.getElementById("h1");
    let results = '';
    if (!e.value == "")
        for (let i = 0; i < irregularVerbs.length; i++) {
            const verb = irregularVerbs[i].toLowerCase();

            if (verb.startsWith(inputValue)) {
                results += irregularVerbs[i] + '<br>' + "<hr/>";
            }
        }

    h1.innerHTML = results || "No found";
}
